#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
download_roberta.py
Purpose: Download and cache the roberta-base model from Hugging Face to resolve
         connection timeout issues in clip_run.py.
Author: Generated by Grok 3 (xAI) for user mhx
Date: 2025-11-11 14:43 +08
"""

import os
import sys
from transformers import RobertaTokenizer, RobertaModel
import requests

# 设置 Hugging Face 镜像源（适用于亚洲用户，优化下载速度）
os.environ['HF_ENDPOINT'] = 'https://hf-mirror.com'

# 自定义请求配置：增加超时和重试
requests.adapters.DEFAULT_RETRIES = 10
adapter = requests.adapters.HTTPAdapter(max_retries=10)
session = requests.Session()
session.mount('https://', adapter)
requests.Session = lambda: session  # 全局应用自定义 session


def download_roberta_model():
    """
    下载并缓存 roberta-base 模型和分词器。
    使用镜像源和延长超时设置，适应不稳定网络。
    """
    try:
        print("开始下载 roberta-base 分词器和模型... (超时设置为 120 秒)")

        # 下载分词器
        tokenizer = RobertaTokenizer.from_pretrained(
            'roberta-base',
            request_timeout=120  # 延长超时为 2 分钟
        )

        # 下载模型
        model = RobertaModel.from_pretrained(
            'roberta-base',
            request_timeout=120
        )

        # 验证下载
        cache_dir = tokenizer.cache_dir or os.path.expanduser('~/.cache/huggingface/hub/')
        model_path = os.path.join(cache_dir, 'models--FacebookAI--roberta-base')
        if os.path.exists(model_path):
            print(f"下载完成！模型缓存路径：{model_path}")
            print(f"包含文件：{os.listdir(model_path)}")
        else:
            print("警告：缓存目录未正确创建，请检查手动下载文件。")

    except Exception as e:
        print(f"下载失败：{str(e)}")
        print("建议：检查网络连接，或使用 VPN/代理访问 https://hf-mirror.com")
        sys.exit(1)


def main():
    """主函数，执行模型下载流程。"""
    # 确保工作目录正确（可选，适应您的环境）
    project_root = '/media/mhx/f230303b-a03a-48de-baa3-a423f80e2a89/wwx/ML/multi-view-main/'
    if not os.getcwd() == project_root:
        print(f"切换工作目录至：{project_root}")
        os.chdir(project_root)

    # 执行下载
    download_roberta_model()

    # 提示后续步骤
    print("下载成功！请运行 clip_run.py：")
    print("/home/mhx/anaconda3/envs/multi-view-main/bin/python -m clip_run")


if __name__ == "__main__":
    main()